name: GuildManager
version: ${project.version}
main: com.mcatk.guildmanager.GuildManager
authors: [ soto ]
website: www.mcatk.com
depend: [Vault]
softdepend: [PlaceholderAPI]
commands:
  gmg:
    description: main command
  gmgadmin:
    description: admin command